#export PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
export PATH=~/bin:$PATH
shopt -s histappend
export HISTFILESIZE=100000
export HISTSIZE=10000000
export PS1='\u \H \w '
alias vi=nvim

