default: &default
  host: db
  username: postgres
  password: password
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= "#{ENV['app_name']}_dev" %>

test:
  <<: *default
  database: <%= "#{ENV['app_name']}_test" %>

production:
  <<: *default
  database: <%= "#{ENV['app_name']}_prod" %>

